### ISSUE TITLE
build failed on g++ 4.8.4

### ISSUE THREAD

**Issue by wonnyz** [joyieldInc/predixy#30]
I tried to build predixy on Ubuntu 14.04, g++ 4.8.4 and it failed.

```
$ make -j 8
make[1]: Entering directory `/home/user/predixy/src'
make[1]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
g++ -std=c++11 -Wall -w -g -O3 -D_PREDIXY_BACKTRACE_ -D_EPOLL_ -c Crc16.cpp
g++ -std=c++11 -Wall -w -g -O3 -D_PREDIXY_BACKTRACE_ -D_EPOLL_ -c HashFunc.cpp
g++ -std=c++11 -Wall -w -g -O3 -D_PREDIXY_BACKTRACE_ -D_EPOLL_ -c Timer.cpp
g++ -std=c++11 -Wall -w -g -O3 -D_PREDIXY_BACKTRACE_ -D_EPOLL_ -c Logger.cpp
g++ -std=c++11 -Wall -w -g -O3 -D_PREDIXY_BACKTRACE_ -D_EPOLL_ -c LogFileSink.cpp
g++ -std=c++11 -Wall -w -g -O3 -D_PREDIXY_BACKTRACE_ -D_EPOLL_ -c Alloc.cpp
g++ -std=c++11 -Wall -w -g -O3 -D_PREDIXY_BACKTRACE_ -D_EPOLL_ -c Socket.cpp
g++ -std=c++11 -Wall -w -g -O3 -D_PREDIXY_BACKTRACE_ -D_EPOLL_ -c ListenSocket.cpp
g++ -std=c++11 -Wall -w -g -O3 -D_PREDIXY_BACKTRACE_ -D_EPOLL_ -c AcceptSocket.cpp
g++ -std=c++11 -Wall -w -g -O3 -D_PREDIXY_BACKTRACE_ -D_EPOLL_ -c ConnectSocket.cpp
g++ -std=c++11 -Wall -w -g -O3 -D_PREDIXY_BACKTRACE_ -D_EPOLL_ -c EpollMultiplexor.cpp
g++ -std=c++11 -Wall -w -g -O3 -D_PREDIXY_BACKTRACE_ -D_EPOLL_ -c Subscribe.cpp
g++ -std=c++11 -Wall -w -g -O3 -D_PREDIXY_BACKTRACE_ -D_EPOLL_ -c Connection.cpp
g++ -std=c++11 -Wall -w -g -O3 -D_PREDIXY_BACKTRACE_ -D_EPOLL_ -c AcceptConnection.cpp
g++ -std=c++11 -Wall -w -g -O3 -D_PREDIXY_BACKTRACE_ -D_EPOLL_ -c ConnectConnection.cpp
g++ -std=c++11 -Wall -w -g -O3 -D_PREDIXY_BACKTRACE_ -D_EPOLL_ -c Buffer.cpp
g++ -std=c++11 -Wall -w -g -O3 -D_PREDIXY_BACKTRACE_ -D_EPOLL_ -c Command.cpp

In file included from Command.h:11:0,
                 from Command.cpp:11:
Command.h: In instantiation of ‘Command::InitFail::InitFail(A&& ...) [with A = {const char (&)[12], int, const char (&)[32], const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&}]’:
Command.cpp:199:9:   required from here
Exception.h:58:41: error: cannot pass objects of non-trivially-copyable type ‘const class std::basic_string<char>’ through ‘...’
     T(A&&... args):ExceptionBase(args...) {}            \
                                         ^
Command.h:19:5: note: in expansion of macro ‘DefException’
     DefException(InitFail);
     ^
make[1]: *** [Command.o] Error 1
make[1]: Leaving directory `/home/fo3-mgr/predixy/src'
make: *** [default] Error 2

$ g++ --version
g++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
FYI, build on g++ 5.4.0 (Ubuntu 16.04) was successful.

**Comment by fortrue** [comment]
thank you, fix it  a856f26

**Comment by wonnyz** [comment]
confirmed working! thank you very much 😄

**Comment by fortrue** [comment]
good suggestion, fix it 28edb79
